// Code generated by microgen 1.0.5. DO NOT EDIT.

package transport

import endpoint "github.com/go-kit/kit/endpoint"

// EndpointsSet implements Service API and used for transport purposes.
type OneToManyStreamEndpoint func(req interface{}, stream interface{}) error

type ManyToManyStreamEndpoint func(stream interface{}) error

type ManyToOneStreamEndpoint func(stream interface{}) error

type EndpointsSet struct {
	CreateServiceEndpoint            endpoint.Endpoint
	GetAllServicesEndpoint           endpoint.Endpoint
	GetServiceEndpoint               endpoint.Endpoint
	CreateAccountEndpoint            endpoint.Endpoint
	CreateAccountWithNameEndpoint    endpoint.Endpoint
	GetAllAccountsEndpoint           endpoint.Endpoint
	GetAccountEndpoint               endpoint.Endpoint
	UpdateAccountEndpoint            endpoint.Endpoint
	AttachAccountToServiceEndpoint   endpoint.Endpoint
	RemoveAccountFromServiceEndpoint endpoint.Endpoint
	CreatePermissionEndpoint         endpoint.Endpoint
	GetPermissionEndpoint            endpoint.Endpoint
	GetAllPermissionEndpoint         endpoint.Endpoint
	GetFilteredPermissionsEndpoint   endpoint.Endpoint
	DeletePermissionEndpoint         endpoint.Endpoint
	GetUserPermissionsEndpoint       endpoint.Endpoint
	AddUserPermissionEndpoint        endpoint.Endpoint
	RemoveUserPermissionEndpoint     endpoint.Endpoint
}
