// Code generated by microgen 1.0.5. DO NOT EDIT.

package transportgrpc

import (
	pb "auth/auth/proto"
	transport "auth/auth/transport"
	grpckit "github.com/go-kit/kit/transport/grpc"
	grpc "google.golang.org/grpc"
)

func NewGRPCClient(conn *grpc.ClientConn, addr string, opts ...grpckit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{
		LoginEndpoint: grpckit.NewClient(
			conn, addr, "Login",
			_Encode_Login_Request,
			_Decode_Login_Response,
			pb.LoginResponse{},
			opts...,
		).Endpoint(),
		PublicKeyEndpoint: grpckit.NewClient(
			conn, addr, "PublicKey",
			_Encode_PublicKey_Request,
			_Decode_PublicKey_Response,
			pb.PublicKeyResponse{},
			opts...,
		).Endpoint(),
		RegisterEndpoint: grpckit.NewClient(
			conn, addr, "Register",
			_Encode_Register_Request,
			_Decode_Register_Response,
			pb.RegisterResponse{},
			opts...,
		).Endpoint(),
	}
}
