// Code generated by microgen 1.0.5. DO NOT EDIT.

package transport

import (
	types "auth/pkg/types"
	"context"
)

func (set EndpointsSet) Register(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 uint) (res0 bool, res1 error) {
	request := RegisterRequest{
		AccountID: arg4,
		Login:     arg1,
		Password:  arg2,
		Service:   arg3,
	}
	response, res1 := set.RegisterEndpoint(arg0, &request)
	if res1 != nil {
		return
	}
	return response.(*RegisterResponse).Ok, res1
}

func (set EndpointsSet) Login(arg0 context.Context, arg1 string, arg2 string, arg3 string) (res0 types.AccessToken, res1 error) {
	request := LoginRequest{
		Login:    arg1,
		Password: arg2,
		Service:  arg3,
	}
	response, res1 := set.LoginEndpoint(arg0, &request)
	if res1 != nil {
		return
	}
	return response.(*LoginResponse).At, res1
}
