// Code generated by microgen 1.0.5. DO NOT EDIT.

package transport

import types "auth/pkg/types"

type (
	RegisterRequest struct {
		Login     string `json:"login"`
		Password  string `json:"password"`
		Service   string `json:"service"`
		AccountID uint   `json:"account_id"`
	}
	RegisterResponse struct {
		Ok bool `json:"ok"`
	}

	LoginRequest struct {
		Login    string `json:"login"`
		Password string `json:"password"`
		Service  string `json:"service"`
	}
	LoginResponse struct {
		At types.AccessToken `json:"at"`
	}
)
