// Code generated by microgen 1.0.5. DO NOT EDIT.

package service

import (
	service "auth/auth"
	types "auth/pkg/types"
	"context"
	log "github.com/go-kit/kit/log"
	"time"
)

// LoggingMiddleware writes params, results and working time of method call to provided logger after its execution.
func LoggingMiddleware(logger log.Logger) Middleware {
	return func(next service.Service) service.Service {
		return &loggingMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type loggingMiddleware struct {
	logger log.Logger
	next   service.Service
}

func (M loggingMiddleware) Register(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 uint) (res0 bool, res1 error) {
	defer func(begin time.Time) {
		M.logger.Log(
			"method", "Register",
			"message", "Register called",
			"request", logRegisterRequest{
				AccountID: arg4,
				Login:     arg1,
				Password:  arg2,
				Service:   arg3,
			},
			"response", logRegisterResponse{Ok: res0},
			"err", res1,
			"took", time.Since(begin))
	}(time.Now())
	return M.next.Register(arg0, arg1, arg2, arg3, arg4)
}

func (M loggingMiddleware) Login(arg0 context.Context, arg1 string, arg2 string, arg3 string) (res0 types.AccessToken, res1 error) {
	defer func(begin time.Time) {
		M.logger.Log(
			"method", "Login",
			"message", "Login called",
			"request", logLoginRequest{
				Login:    arg1,
				Password: arg2,
				Service:  arg3,
			},
			"response", logLoginResponse{At: res0},
			"err", res1,
			"took", time.Since(begin))
	}(time.Now())
	return M.next.Login(arg0, arg1, arg2, arg3)
}

type (
	logRegisterRequest struct {
		Login     string
		Password  string
		Service   string
		AccountID uint
	}
	logRegisterResponse struct {
		Ok bool
	}
	logLoginRequest struct {
		Login    string
		Password string
		Service  string
	}
	logLoginResponse struct {
		At types.AccessToken
	}
)
