// Code generated by microgen 1.0.5. DO NOT EDIT.

package service

import (
	service "auth/auth"
	types "auth/pkg/types"
	"context"
	"fmt"
	log "github.com/go-kit/kit/log"
)

// RecoveringMiddleware recovers panics from method calls, writes to provided logger and returns the error of panic as method error.
func RecoveringMiddleware(logger log.Logger) Middleware {
	return func(next service.Service) service.Service {
		return &recoveringMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type recoveringMiddleware struct {
	logger log.Logger
	next   service.Service
}

func (M recoveringMiddleware) Register(ctx context.Context, login string, password string, service string, accountID uint) (ok bool, err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "Register", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.Register(ctx, login, password, service, accountID)
}

func (M recoveringMiddleware) Login(ctx context.Context, login string, password string, service string) (at types.AccessToken, err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "Login", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.Login(ctx, login, password, service)
}
