// Code generated by "stringer -type Access"; DO NOT EDIT.

package access

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Active-1]
	_ = x[SelfLedger-2]
	_ = x[ReadLedger-4]
	_ = x[WriteLedger-8]
}

const (
	_Access_name_0 = "ActiveSelfLedger"
	_Access_name_1 = "ReadLedger"
	_Access_name_2 = "WriteLedger"
)

var (
	_Access_index_0 = [...]uint8{0, 6, 16}
)

func (i Access) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Access_name_0[_Access_index_0[i]:_Access_index_0[i+1]]
	case i == 4:
		return _Access_name_1
	case i == 8:
		return _Access_name_2
	default:
		return "Access(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
