// Code generated by microgen 1.0.5. DO NOT EDIT.

package service

import service "github.com/nullc4t/auth-service/pkg/mgmt"

// Service middleware (closure).
type Middleware func(service.Service) service.Service
